---
- hosts: qaserver
  become: true
  ignore_errors: yes
  tasks:
    - name: Install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - unzip
        - wget
        - httpd
      become: true

    - name: Download repository
      command: wget https://github.com/utrains/static-resume/archive/refs/heads/main.zip
      args:
        chdir: /tmp

    - name: Unzip repository
      command: unzip main.zip -d /tmp
      args:
        creates: /tmp/static-resume-main

    - name: Copy files to web server directory
      command: cp -r /tmp/static-resume-main/iPortfolio/* /var/www/html/

    - name: Start Apache HTTP server
      service:
        name: httpd
        state: started
        enabled: true

